package br.com.project.view;

import br.com.project.dao.ClientDao;
import br.com.project.model.Client;
import br.com.project.model.Utilities;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class JfClient extends javax.swing.JFrame {

    private ClientDao clientDao;
    private Client client;

//    METODO LISTAR TABELA
    public void listClient() {
        clientDao = new ClientDao();
        List<Client> dataClient = clientDao.listClients();
        DefaultTableModel dataTable = (DefaultTableModel) clientTable.getModel();
        dataTable.setNumRows(0);

        for (Client client1 : dataClient) {
            dataTable.addRow(new Object[]{
                client1.getId(),
                client1.getName(),
                client1.getIdentityDocument(),
                client1.getIndividualRegistration(),
                client1.getEmail(),
                client1.getPhone(),
                client1.getCellPhone(),
                client1.getZipCode(),
                client1.getAddress(),
                client1.getNumber(),
                client1.getComplement(),
                client1.getNeighborhood(),
                client1.getCity(),
                client1.getState()
            });
        }
    }

    public JfClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customer_consultation_panel = new javax.swing.JTabbedPane();
        personal_data_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comBoxStateClient = new javax.swing.JComboBox<>();
        txtPhoneClient = new javax.swing.JFormattedTextField();
        txtNumberClient = new javax.swing.JTextField();
        txtComplementClient = new javax.swing.JTextField();
        txtCityClient = new javax.swing.JTextField();
        txtAddressClient = new javax.swing.JTextField();
        txtIndividualRegistrationClient = new javax.swing.JFormattedTextField();
        txtIdentityDocumentClient = new javax.swing.JTextField();
        txtNeighborhoodClient = new javax.swing.JTextField();
        txtZipCodeClient = new javax.swing.JFormattedTextField();
        txtEmailClient = new javax.swing.JTextField();
        txtNameClient = new javax.swing.JTextField();
        txtKeyClient = new javax.swing.JTextField();
        txtCellPhoneClient = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtSearchClient = new javax.swing.JTextField();
        buttonSearchClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonChange = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        customer_consultation_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_consultation_panelMouseClicked(evt);
            }
        });

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nome:");

        jLabel4.setText("E-mail:");

        jLabel5.setText("CEP:");

        jLabel6.setText("Bairro:");

        jLabel7.setText("RG:");

        jLabel8.setText("Endereço:");

        jLabel9.setText("Cidade:");

        jLabel10.setText("CPF:");

        jLabel11.setText("Celular:");

        jLabel12.setText("Complemento:");

        jLabel13.setText("Telefone Fixo:");

        jLabel14.setText("Nº:");

        jLabel15.setText("UF:");

        comBoxStateClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        comBoxStateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxStateClientActionPerformed(evt);
            }
        });

        try {
            txtPhoneClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhoneClient.setMinimumSize(new java.awt.Dimension(4, 24));
        txtPhoneClient.setPreferredSize(new java.awt.Dimension(55, 24));

        txtComplementClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementClientActionPerformed(evt);
            }
        });

        try {
            txtIndividualRegistrationClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ### - ### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIndividualRegistrationClient.setMinimumSize(new java.awt.Dimension(4, 24));
        txtIndividualRegistrationClient.setPreferredSize(new java.awt.Dimension(67, 24));

        try {
            txtZipCodeClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtZipCodeClient.setMinimumSize(new java.awt.Dimension(4, 24));
        txtZipCodeClient.setPreferredSize(new java.awt.Dimension(38, 24));
        txtZipCodeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeClientActionPerformed(evt);
            }
        });

        txtEmailClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClientActionPerformed(evt);
            }
        });

        txtNameClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameClientActionPerformed(evt);
            }
        });

        try {
            txtCellPhoneClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCellPhoneClient.setMinimumSize(new java.awt.Dimension(14, 22));
        txtCellPhoneClient.setPreferredSize(new java.awt.Dimension(14, 22));

        javax.swing.GroupLayout personal_data_panelLayout = new javax.swing.GroupLayout(personal_data_panel);
        personal_data_panel.setLayout(personal_data_panelLayout);
        personal_data_panelLayout.setHorizontalGroup(
            personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_data_panelLayout.createSequentialGroup()
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKeyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personal_data_panelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCellPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumberClient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personal_data_panelLayout.createSequentialGroup()
                            .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdentityDocumentClient, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNeighborhoodClient, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtZipCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAddressClient, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comBoxStateClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIndividualRegistrationClient, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCityClient, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtComplementClient, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        personal_data_panelLayout.setVerticalGroup(
            personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKeyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCellPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtNumberClient))
                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11)
                        .addComponent(txtEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(txtAddressClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(comBoxStateClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtZipCodeClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNeighborhoodClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCityClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtComplementClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdentityDocumentClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtIndividualRegistrationClient, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        customer_consultation_panel.addTab("Dados Pessoais", personal_data_panel);

        jLabel16.setText("Nome:");

        txtSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchClientActionPerformed(evt);
            }
        });
        txtSearchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchClientKeyPressed(evt);
            }
        });

        buttonSearchClient.setText("Pesquisar");
        buttonSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchClientActionPerformed(evt);
            }
        });

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "RG", "CPF", "E-mail", "Telefone", "Celular", "CEP", "Endereço", "Nº", "Comp", "Bairro", "Cidade", "UF"
            }
        ));
        clientTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                clientTableComponentAdded(evt);
            }
        });
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSearchClient)
                        .addGap(0, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        customer_consultation_panel.addTab("Consulta de Clientes", jPanel3);

        buttonNew.setText("Novo");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonChange.setText("Editar");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        buttonDelete.setText("Excluir");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(buttonNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_consultation_panel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customer_consultation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNew)
                    .addComponent(buttonSave)
                    .addComponent(buttonChange)
                    .addComponent(buttonDelete))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comBoxStateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxStateClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxStateClientActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // BOTAO SALVAR

        client = new Client();

        client.setName(txtNameClient.getText());
        client.setIdentityDocument(txtIdentityDocumentClient.getText());
        client.setIndividualRegistration(txtIndividualRegistrationClient.getText());
        client.setEmail(txtEmailClient.getText());
        client.setPhone(txtPhoneClient.getText());
        client.setCellPhone(txtCellPhoneClient.getText());
        client.setZipCode(txtZipCodeClient.getText());
        client.setAddress(txtAddressClient.getText());
        client.setNumber(Integer.parseInt(txtNumberClient.getText()));
        client.setComplement(txtComplementClient.getText());
        client.setNeighborhood(txtNeighborhoodClient.getText());
        client.setCity(txtCityClient.getText());
        client.setState(comBoxStateClient.getSelectedItem().toString());

        clientDao = new ClientDao();
        clientDao.registerClient(client);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void txtSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchClientActionPerformed

    private void buttonSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchClientActionPerformed
//        BOTÃO PESQUISAR 
        String name = txtSearchClient.getText();
        clientDao = new ClientDao();
        List<Client> dataClient = clientDao.searchClientByName(name);
        DefaultTableModel dataTable = (DefaultTableModel) clientTable.getModel();
        dataTable.setNumRows(0);

        for (Client client1 : dataClient) {
            dataTable.addRow(new Object[]{
                client1.getId(),
                client1.getName(),
                client1.getIdentityDocument(),
                client1.getIndividualRegistration(),
                client1.getEmail(),
                client1.getPhone(),
                client1.getCellPhone(),
                client1.getZipCode(),
                client1.getAddress(),
                client1.getNumber(),
                client1.getComplement(),
                client1.getNeighborhood(),
                client1.getCity(),
                client1.getState()
            });
        }
    }//GEN-LAST:event_buttonSearchClientActionPerformed

    private void clientTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_clientTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTableComponentAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        CARREGAR LISTA
        listClient();
    }//GEN-LAST:event_formWindowActivated

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
//        PEGAR OS DADOS
        customer_consultation_panel.setSelectedIndex(0);

        txtKeyClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 0).toString());
        txtNameClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 1).toString());
        txtIdentityDocumentClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 2).toString());
        txtIndividualRegistrationClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 3).toString());
        txtEmailClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 4).toString());
        txtPhoneClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 5).toString());
        txtCellPhoneClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 6).toString());
        txtZipCodeClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 7).toString());
        txtAddressClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 8).toString());
        txtNumberClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 9).toString());
        txtComplementClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 10).toString());
        txtNeighborhoodClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 11).toString());
        txtCityClient.setText(clientTable.getValueAt(clientTable.getSelectedRow(), 12).toString());
        comBoxStateClient.setSelectedItem(clientTable.getValueAt(clientTable.getSelectedRow(), 13).toString());
//        UTILIZADO PARA MANIPULAÇÃO DOS DADOS AO CLICAR PREENCHE A TELA DE CADASTRO, SENDO POSSIVEL ALTERAR
//        EXCLUIR OU CADASTRAR A ENTIDADE COM NOVAS INFORMAÇÕES  
    }//GEN-LAST:event_clientTableMouseClicked

    private void customer_consultation_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_consultation_panelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_consultation_panelMouseClicked

    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed
//        BOTAO EDITAR
        client = new Client();

        client.setName(txtNameClient.getText());
        client.setIdentityDocument(txtIdentityDocumentClient.getText());
        client.setIndividualRegistration(txtIndividualRegistrationClient.getText());
        client.setEmail(txtEmailClient.getText());
        client.setPhone(txtPhoneClient.getText());
        client.setCellPhone(txtCellPhoneClient.getText());
        client.setZipCode(txtZipCodeClient.getText());
        client.setAddress(txtAddressClient.getText());
        client.setNumber(Integer.parseInt(txtNumberClient.getText()));
        client.setComplement(txtComplementClient.getText());
        client.setNeighborhood(txtNeighborhoodClient.getText());
        client.setCity(txtCityClient.getText());
        client.setState(comBoxStateClient.getSelectedItem().toString());

        client.setId(Integer.parseInt(txtKeyClient.getText()));

        clientDao = new ClientDao();
        clientDao.changeClient(client);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonChangeActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
//      LIMPA OS DADOS DO FORMULARIO
        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
//        BOTAO EXCLUIR
        client = new Client();

        client.setId(Integer.parseInt(txtKeyClient.getText()));

        clientDao = new ClientDao();
        clientDao.deleteClient(client);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void txtSearchClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchClientKeyPressed

        String name = txtSearchClient.getText();
        clientDao = new ClientDao();
        List<Client> dataClient = clientDao.searchClientByName(name);
        DefaultTableModel dataTable = (DefaultTableModel) clientTable.getModel();
        dataTable.setNumRows(0);

        for (Client client1 : dataClient) {
            dataTable.addRow(new Object[]{
                client1.getId(),
                client1.getName(),
                client1.getIdentityDocument(),
                client1.getIndividualRegistration(),
                client1.getEmail(),
                client1.getPhone(),
                client1.getCellPhone(),
                client1.getZipCode(),
                client1.getAddress(),
                client1.getNumber(),
                client1.getComplement(),
                client1.getNeighborhood(),
                client1.getCity(),
                client1.getState()
            });
        }
    }//GEN-LAST:event_txtSearchClientKeyPressed

    private void txtComplementClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementClientActionPerformed

    private void txtNameClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameClientActionPerformed

    private void txtZipCodeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeClientActionPerformed

    private void txtEmailClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChange;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearchClient;
    private javax.swing.JTable clientTable;
    private javax.swing.JComboBox<String> comBoxStateClient;
    public javax.swing.JTabbedPane customer_consultation_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel personal_data_panel;
    private javax.swing.JTextField txtAddressClient;
    private javax.swing.JFormattedTextField txtCellPhoneClient;
    private javax.swing.JTextField txtCityClient;
    private javax.swing.JTextField txtComplementClient;
    private javax.swing.JTextField txtEmailClient;
    private javax.swing.JTextField txtIdentityDocumentClient;
    private javax.swing.JFormattedTextField txtIndividualRegistrationClient;
    private javax.swing.JTextField txtKeyClient;
    private javax.swing.JTextField txtNameClient;
    private javax.swing.JTextField txtNeighborhoodClient;
    private javax.swing.JTextField txtNumberClient;
    private javax.swing.JFormattedTextField txtPhoneClient;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JFormattedTextField txtZipCodeClient;
    // End of variables declaration//GEN-END:variables
}
