/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.project.view;

import br.com.project.dao.EmployeeDao;
import br.com.project.model.Employee;
import br.com.project.model.Utilities;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class JfEmployee extends javax.swing.JFrame {

    private EmployeeDao employeeDao;
    private Employee employee;
    private List<Employee> dataEmployee;
    private DefaultTableModel dataTable;

    public void listEmployee() {
        employeeDao = new EmployeeDao();
        dataEmployee = employeeDao.listEmployee();
        dataTable = (DefaultTableModel) employeeTable.getModel();
        dataTable.setNumRows(0);

        for (Employee employee1 : dataEmployee) {
            dataTable.addRow(new Object[]{
                employee1.getId(),
                employee1.getName(),
                employee1.getIdentityDocument(),
                employee1.getIndividualRegistration(),
                employee1.getEmail(),
                employee1.getPhone(),
                employee1.getCellPhone(),
                employee1.getZipCode(),
                employee1.getAddress(),
                employee1.getNumber(),
                employee1.getComplement(),
                employee1.getNeighborhood(),
                employee1.getCity(),
                employee1.getState(),
                employee1.getPassword(),
                employee1.getJobRole(),
                employee1.getAccessLevel()
            });
        }
    }

    public JfEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employee_consultation_panel = new javax.swing.JTabbedPane();
        personal_data_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNameEmployee = new javax.swing.JTextField();
        txtKeyEmployee = new javax.swing.JTextField();
        txtEmailEmployee = new javax.swing.JTextField();
        txtAddressEmployee = new javax.swing.JTextField();
        txtZipCodeEmployee = new javax.swing.JFormattedTextField();
        txtNeighborhoodEmployee = new javax.swing.JTextField();
        txtIdentityDocumentEmployee = new javax.swing.JTextField();
        txtPasswordEmployee = new javax.swing.JPasswordField();
        txtCityEmployee = new javax.swing.JTextField();
        txtIndividualRegistrationEmployee = new javax.swing.JFormattedTextField();
        comBoxAccessLevelEmployee = new javax.swing.JComboBox<>();
        txtJobRoleEmployee = new javax.swing.JTextField();
        txtComplementEmployee = new javax.swing.JTextField();
        txtNumberEmployee = new javax.swing.JTextField();
        txtCellPhoneEmployee = new javax.swing.JFormattedTextField();
        comBoxStateEmployee = new javax.swing.JComboBox<>();
        txtPhoneEmployee = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtSearchEmployee = new javax.swing.JTextField();
        buttonSearchEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonChange = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Funcionários");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nome:");

        jLabel4.setText("RG:");

        jLabel5.setText("CEP:");

        jLabel6.setText("Bairro:");

        jLabel7.setText("E-mai:");

        jLabel8.setText("Senha:");

        jLabel9.setText("Endereço:");

        jLabel10.setText("Cidade:");

        jLabel11.setText("CPF:");

        jLabel12.setText("Nivel de Acesso:");

        jLabel13.setText("Celular:");

        jLabel14.setText("Complemento:");

        jLabel15.setText("Cargo:");

        jLabel16.setText("Telefone Fixo:");

        jLabel17.setText("Nº:");

        jLabel18.setText("UF:");

        txtNameEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameEmployeeActionPerformed(evt);
            }
        });

        txtEmailEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmployeeActionPerformed(evt);
            }
        });

        txtAddressEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressEmployeeActionPerformed(evt);
            }
        });

        try {
            txtZipCodeEmployee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtZipCodeEmployee.setMinimumSize(new java.awt.Dimension(4, 24));
        txtZipCodeEmployee.setPreferredSize(new java.awt.Dimension(41, 24));

        txtPasswordEmployee.setMinimumSize(new java.awt.Dimension(14, 24));
        txtPasswordEmployee.setPreferredSize(new java.awt.Dimension(14, 24));
        txtPasswordEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordEmployeeActionPerformed(evt);
            }
        });

        try {
            txtIndividualRegistrationEmployee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIndividualRegistrationEmployee.setMinimumSize(new java.awt.Dimension(4, 24));
        txtIndividualRegistrationEmployee.setPreferredSize(new java.awt.Dimension(53, 24));

        comBoxAccessLevelEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador" }));
        comBoxAccessLevelEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxAccessLevelEmployeeActionPerformed(evt);
            }
        });

        txtJobRoleEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobRoleEmployeeActionPerformed(evt);
            }
        });

        txtComplementEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementEmployeeActionPerformed(evt);
            }
        });

        txtNumberEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberEmployeeActionPerformed(evt);
            }
        });

        try {
            txtCellPhoneEmployee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCellPhoneEmployee.setMinimumSize(new java.awt.Dimension(4, 24));
        txtCellPhoneEmployee.setPreferredSize(new java.awt.Dimension(61, 24));
        txtCellPhoneEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellPhoneEmployeeActionPerformed(evt);
            }
        });

        comBoxStateEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            txtPhoneEmployee.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhoneEmployee.setMinimumSize(new java.awt.Dimension(4, 24));
        txtPhoneEmployee.setPreferredSize(new java.awt.Dimension(61, 24));
        txtPhoneEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personal_data_panelLayout = new javax.swing.GroupLayout(personal_data_panel);
        personal_data_panel.setLayout(personal_data_panelLayout);
        personal_data_panelLayout.setHorizontalGroup(
            personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_data_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_data_panelLayout.createSequentialGroup()
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPasswordEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentityDocumentEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNeighborhoodEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtZipCodeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comBoxAccessLevelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAddressEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumberEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personal_data_panelLayout.createSequentialGroup()
                                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(personal_data_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCityEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(personal_data_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtIndividualRegistrationEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(personal_data_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtComplementEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(personal_data_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtJobRoleEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_data_panelLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comBoxStateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(personal_data_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtCellPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personal_data_panelLayout.createSequentialGroup()
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtKeyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personal_data_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personal_data_panelLayout.setVerticalGroup(
            personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_data_panelLayout.createSequentialGroup()
                .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personal_data_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personal_data_panelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtCellPhoneEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxStateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtZipCodeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddressEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumberEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNeighborhoodEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtCityEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComplementEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdentityDocumentEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtIndividualRegistrationEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJobRoleEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personal_data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(comBoxAccessLevelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        employee_consultation_panel.addTab("Dados Pessoais", personal_data_panel);

        jLabel19.setText("Nome:");

        txtSearchEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchEmployeeKeyPressed(evt);
            }
        });

        buttonSearchEmployee.setText("Pesquisar");
        buttonSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchEmployeeActionPerformed(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "RG", "CPF", "E-mail", "Senha", "Cargo", "Nivel de Acesso", "Telefone", "Celular", "CEP", "Endereço", "Nº", "Comp", "Bairro", "Cidade", "UF"
            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSearchEmployee)
                        .addGap(0, 290, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        employee_consultation_panel.addTab("Consulta de Funcionários ", jPanel4);

        buttonNew.setText("Novo");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonChange.setText("Editar");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        buttonDelete.setText("Excluir");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(employee_consultation_panel)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(buttonNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employee_consultation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChange)
                    .addComponent(buttonSave)
                    .addComponent(buttonNew)
                    .addComponent(buttonDelete))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listEmployee();
    }//GEN-LAST:event_formWindowActivated

    private void txtNameEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEmployeeActionPerformed

    private void txtEmailEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmployeeActionPerformed

    private void txtAddressEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressEmployeeActionPerformed

    private void txtPasswordEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordEmployeeActionPerformed

    private void comBoxAccessLevelEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxAccessLevelEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxAccessLevelEmployeeActionPerformed

    private void txtJobRoleEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobRoleEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobRoleEmployeeActionPerformed

    private void txtComplementEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementEmployeeActionPerformed

    private void txtNumberEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberEmployeeActionPerformed

    private void txtCellPhoneEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellPhoneEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellPhoneEmployeeActionPerformed

    private void txtPhoneEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneEmployeeActionPerformed

    private void txtSearchEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEmployeeKeyPressed

        String name = txtSearchEmployee.getText();
        employeeDao = new EmployeeDao();
        dataEmployee = employeeDao.searchEmployeeByName(name);
        dataTable = (DefaultTableModel) employeeTable.getModel();
        dataTable.setNumRows(0);

        for (Employee employee1 : dataEmployee) {
            dataTable.addRow(new Object[]{
                employee1.getId(),
                employee1.getName(),
                employee1.getIdentityDocument(),
                employee1.getIndividualRegistration(),
                employee1.getEmail(),
                employee1.getPhone(),
                employee1.getCellPhone(),
                employee1.getZipCode(),
                employee1.getAddress(),
                employee1.getNumber(),
                employee1.getComplement(),
                employee1.getNeighborhood(),
                employee1.getCity(),
                employee1.getState(),
                employee1.getPassword(),
                employee1.getJobRole(),
                employee1.getAccessLevel()
            });
        }
    }//GEN-LAST:event_txtSearchEmployeeKeyPressed

    private void buttonSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchEmployeeActionPerformed
        String name = txtSearchEmployee.getText();
        employeeDao = new EmployeeDao();
        dataEmployee = employeeDao.searchEmployeeByName(name);
        dataTable = (DefaultTableModel) employeeTable.getModel();
        dataTable.setNumRows(0);

        for (Employee employee1 : dataEmployee) {
            dataTable.addRow(new Object[]{
                employee1.getId(),
                employee1.getName(),
                employee1.getIdentityDocument(),
                employee1.getIndividualRegistration(),
                employee1.getEmail(),
                employee1.getPhone(),
                employee1.getCellPhone(),
                employee1.getZipCode(),
                employee1.getAddress(),
                employee1.getNumber(),
                employee1.getComplement(),
                employee1.getNeighborhood(),
                employee1.getCity(),
                employee1.getState(),
                employee1.getPassword(),
                employee1.getJobRole(),
                employee1.getAccessLevel()
            });
        }
    }//GEN-LAST:event_buttonSearchEmployeeActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked

        employee_consultation_panel.setSelectedIndex(0);

        txtKeyEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 0).toString());
        txtNameEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 1).toString());
        txtIdentityDocumentEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 2).toString());
        txtIndividualRegistrationEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 3).toString());
        txtEmailEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 4).toString());
        txtPhoneEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 5).toString());
        txtCellPhoneEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 6).toString());
        txtZipCodeEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 7).toString());
        txtAddressEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 8).toString());
        txtNumberEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 9).toString());
        txtComplementEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 10).toString());
        txtNeighborhoodEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 11).toString());
        txtCityEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 12).toString());
        comBoxStateEmployee.setSelectedItem(employeeTable.getValueAt(employeeTable.getSelectedRow(), 13).toString());
        txtPasswordEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 14).toString());
        txtJobRoleEmployee.setText(employeeTable.getValueAt(employeeTable.getSelectedRow(), 15).toString());
        comBoxAccessLevelEmployee.setSelectedItem(employeeTable.getValueAt(employeeTable.getSelectedRow(), 16).toString());
    }//GEN-LAST:event_employeeTableMouseClicked

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        employee = new Employee();

        employee.setName(txtNameEmployee.getText());
        employee.setIdentityDocument(txtIdentityDocumentEmployee.getText());
        employee.setIndividualRegistration(txtIndividualRegistrationEmployee.getText());
        employee.setEmail(txtEmailEmployee.getText());
        employee.setPhone(txtPhoneEmployee.getText());
        employee.setCellPhone(txtCellPhoneEmployee.getText());
        employee.setZipCode(txtZipCodeEmployee.getText());
        employee.setAddress(txtAddressEmployee.getText());
        employee.setNumber(Integer.parseInt(txtNumberEmployee.getText()));
        employee.setComplement(txtComplementEmployee.getText());
        employee.setNeighborhood(txtNeighborhoodEmployee.getText());
        employee.setCity(txtCityEmployee.getText());
        employee.setState(comBoxStateEmployee.getSelectedItem().toString());
        employee.setPassword(txtPasswordEmployee.getPassword().toString());
        employee.setJobRole(txtJobRoleEmployee.getText());
        employee.setAccessLevel(comBoxAccessLevelEmployee.getSelectedItem().toString());

        employeeDao = new EmployeeDao();
        employeeDao.registerEmployee(employee);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed

        employee = new Employee();

        employee.setName(txtNameEmployee.getText());
        employee.setIdentityDocument(txtIdentityDocumentEmployee.getText());
        employee.setIndividualRegistration(txtIndividualRegistrationEmployee.getText());
        employee.setEmail(txtEmailEmployee.getText());
        employee.setPhone(txtPhoneEmployee.getText());
        employee.setCellPhone(txtCellPhoneEmployee.getText());
        employee.setZipCode(txtZipCodeEmployee.getText());
        employee.setAddress(txtAddressEmployee.getText());
        employee.setNumber(Integer.parseInt(txtNumberEmployee.getText()));
        employee.setComplement(txtComplementEmployee.getText());
        employee.setNeighborhood(txtNeighborhoodEmployee.getText());
        employee.setCity(txtCityEmployee.getText());
        employee.setState(comBoxStateEmployee.getSelectedItem().toString());
        employee.setPassword(txtPasswordEmployee.getPassword().toString());
        employee.setJobRole(txtJobRoleEmployee.getText());
        employee.setAccessLevel(comBoxAccessLevelEmployee.getSelectedItem().toString());

        employee.setId(Integer.parseInt(txtKeyEmployee.getText()));

        employeeDao = new EmployeeDao();
        employeeDao.changeEmployee(employee);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonChangeActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        employee = new Employee();

        employee.setId(Integer.parseInt(txtKeyEmployee.getText()));

        employeeDao = new EmployeeDao();
        employeeDao.deleteEmployee(employee);

        new Utilities().cleanScreen(personal_data_panel);
    }//GEN-LAST:event_buttonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChange;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearchEmployee;
    private javax.swing.JComboBox<String> comBoxAccessLevelEmployee;
    private javax.swing.JComboBox<String> comBoxStateEmployee;
    private javax.swing.JTable employeeTable;
    public javax.swing.JTabbedPane employee_consultation_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel personal_data_panel;
    private javax.swing.JTextField txtAddressEmployee;
    private javax.swing.JFormattedTextField txtCellPhoneEmployee;
    private javax.swing.JTextField txtCityEmployee;
    private javax.swing.JTextField txtComplementEmployee;
    private javax.swing.JTextField txtEmailEmployee;
    private javax.swing.JTextField txtIdentityDocumentEmployee;
    private javax.swing.JFormattedTextField txtIndividualRegistrationEmployee;
    private javax.swing.JTextField txtJobRoleEmployee;
    private javax.swing.JTextField txtKeyEmployee;
    private javax.swing.JTextField txtNameEmployee;
    private javax.swing.JTextField txtNeighborhoodEmployee;
    private javax.swing.JTextField txtNumberEmployee;
    private javax.swing.JPasswordField txtPasswordEmployee;
    private javax.swing.JFormattedTextField txtPhoneEmployee;
    private javax.swing.JTextField txtSearchEmployee;
    private javax.swing.JFormattedTextField txtZipCodeEmployee;
    // End of variables declaration//GEN-END:variables
}
