package br.com.project.view;

import br.com.project.jdbc.TestConnection;
import javax.swing.JOptionPane;

public class JfMenu extends javax.swing.JFrame {

    /**
     * Creates new form JfMenu
     */
    public JfMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuClient = new javax.swing.JMenu();
        menuClientControl = new javax.swing.JMenuItem();
        menuEmployee = new javax.swing.JMenu();
        menuemployeeControl = new javax.swing.JMenuItem();
        menuProvider = new javax.swing.JMenu();
        menuProviderControl = new javax.swing.JMenuItem();
        menuProduct = new javax.swing.JMenu();
        menuStockControl = new javax.swing.JMenuItem();
        menuProductQuery = new javax.swing.JMenuItem();
        menuSale = new javax.swing.JMenu();
        menuOpenPdv = new javax.swing.JMenuItem();
        menuSalesHistory = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuChangeUser = new javax.swing.JMenuItem();
        menuCheckConnection = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        menuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        menuClient.setText("Clientes");

        menuClientControl.setText("Controle de Clientes");
        menuClientControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientControlActionPerformed(evt);
            }
        });
        menuClient.add(menuClientControl);

        jMenuBar1.add(menuClient);

        menuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funcionarios.png"))); // NOI18N
        menuEmployee.setText("Funcionários");

        menuemployeeControl.setText("Controle de Funcionário");
        menuemployeeControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuemployeeControlActionPerformed(evt);
            }
        });
        menuEmployee.add(menuemployeeControl);

        jMenuBar1.add(menuEmployee);

        menuProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fornecedores.png"))); // NOI18N
        menuProvider.setText("Fornecedores");

        menuProviderControl.setText("Controle de Fornecedores");
        menuProviderControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProviderControlActionPerformed(evt);
            }
        });
        menuProvider.add(menuProviderControl);

        jMenuBar1.add(menuProvider);

        menuProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtos.png"))); // NOI18N
        menuProduct.setText("Produtos");
        menuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductActionPerformed(evt);
            }
        });

        menuStockControl.setText("Controle de Estoque");
        menuStockControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockControlActionPerformed(evt);
            }
        });
        menuProduct.add(menuStockControl);

        menuProductQuery.setText("Consulta de Produtos");
        menuProductQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductQueryActionPerformed(evt);
            }
        });
        menuProduct.add(menuProductQuery);

        jMenuBar1.add(menuProduct);

        menuSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendas.png"))); // NOI18N
        menuSale.setText("Vendas");

        menuOpenPdv.setText("Abrir PDV");
        menuOpenPdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenPdvActionPerformed(evt);
            }
        });
        menuSale.add(menuOpenPdv);

        menuSalesHistory.setText("Histórico de Vendas");
        menuSale.add(menuSalesHistory);

        jMenuBar1.add(menuSale);

        menuConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracoes.png"))); // NOI18N
        menuConfig.setText("Configurações");

        menuChangeUser.setText("Troca de Usuário");
        menuChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangeUserActionPerformed(evt);
            }
        });
        menuConfig.add(menuChangeUser);

        menuCheckConnection.setText("Verificar Conexão");
        menuCheckConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheckConnectionActionPerformed(evt);
            }
        });
        menuConfig.add(menuCheckConnection);

        jMenuBar1.add(menuConfig);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
        menuExit.setText("Sair");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setExtendedState(JfMenu.MAXIMIZED_BOTH);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void menuChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangeUserActionPerformed
        try {
            JfLogin jfLogin = new JfLogin();
            int option;
            option = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja trocar de usuário?");

            if (option == 0) {
                jfLogin.setVisible(true);
                this.dispose();
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Erro: " + err);
        }

    }//GEN-LAST:event_menuChangeUserActionPerformed

    private void menuCheckConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheckConnectionActionPerformed
//        TESTAR CONEXÃO
        TestConnection testConnection = new TestConnection();
        testConnection.testConnection();
    }//GEN-LAST:event_menuCheckConnectionActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuClientControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientControlActionPerformed
//        ABRIR TELA DE CLIENTES
        JfClient jfClient = new JfClient();
        jfClient.customer_consultation_panel.setSelectedIndex(1);
        jfClient.setVisible(true);

    }//GEN-LAST:event_menuClientControlActionPerformed

    private void menuemployeeControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuemployeeControlActionPerformed
//        ABRIR TELA DE FUNCIONARIOS
        JfEmployee jfEmployee = new JfEmployee();
        jfEmployee.employee_consultation_panel.setSelectedIndex(1);
        jfEmployee.setVisible(true);
    }//GEN-LAST:event_menuemployeeControlActionPerformed

    private void menuProviderControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProviderControlActionPerformed
//        ABRIR TELA DE FORNECEDORES
        JfProvider jfProvider = new JfProvider();
        jfProvider.provider_consultation_panel.setSelectedIndex(1);
        jfProvider.setVisible(true);
    }//GEN-LAST:event_menuProviderControlActionPerformed

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        int option;
        option = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");

        if (option == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitMouseClicked

    private void menuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductActionPerformed
    }//GEN-LAST:event_menuProductActionPerformed

    private void menuProductQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductQueryActionPerformed
//      ABRIR TELA DE PRODUTOS
        JfProducts jfProducts = new JfProducts();
        jfProducts.product_consultation_panel.setSelectedIndex(1);
        jfProducts.setVisible(true);

    }//GEN-LAST:event_menuProductQueryActionPerformed

    private void menuStockControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockControlActionPerformed
//      ABRIR TELA DE PRODUTOS
        JfProducts jfProducts = new JfProducts();
        jfProducts.product_consultation_panel.setSelectedIndex(1);
        jfProducts.setVisible(true);

    }//GEN-LAST:event_menuStockControlActionPerformed

    private void menuOpenPdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenPdvActionPerformed
//      ABRIR TELA DE VENDAS
        JfSalesScreen jfSales = new JfSalesScreen();
        jfSales.setVisible(true);
    }//GEN-LAST:event_menuOpenPdvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuChangeUser;
    private javax.swing.JMenuItem menuCheckConnection;
    private javax.swing.JMenu menuClient;
    private javax.swing.JMenuItem menuClientControl;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenu menuEmployee;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuOpenPdv;
    private javax.swing.JMenu menuProduct;
    private javax.swing.JMenuItem menuProductQuery;
    private javax.swing.JMenu menuProvider;
    private javax.swing.JMenuItem menuProviderControl;
    private javax.swing.JMenu menuSale;
    private javax.swing.JMenuItem menuSalesHistory;
    private javax.swing.JMenuItem menuStockControl;
    private javax.swing.JMenuItem menuemployeeControl;
    // End of variables declaration//GEN-END:variables
}
